import { imgEight, imgEighteen, imgFifteen, imgFive, imgFour, imgFourteen, imgNine, imgNineteen, imgOne, imgSeven, imgSeventeen, imgSix, imgSixteen, imgTen, imgThirteen, imgThree, imgTwelve, imgTwenty, imgTwentyFive, imgTwentyFour, imgTwentyOne, imgTwentyThree, imgTwentyTwo, imgTwo } from "assets/index";

export const data = [
	{
		id: 1,
		image: imgOne,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 2,
		image: imgTwo,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 3,
		image: imgThree,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 4,
		image: imgFour,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 5,
		image: imgFive,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 6,
		image: imgSix,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 7,
		image: imgSeven,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 8,
		image: imgEight,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 9,
		image: imgNine,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 10,
		image: imgTen,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 11,
		image: imgEighteen,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 12,
		image: imgTwelve,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 13,
		image: imgThirteen,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 14,
		image: imgFourteen,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 15,
		image: imgFifteen,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 16,
		image: imgSixteen,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 17,
		image: imgSeventeen,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 18,
		image: imgEighteen,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 19,
		image: imgNineteen,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 20,
		image: imgTwenty,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 21,
		image: imgTwentyOne,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 22,
		image: imgTwentyTwo,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 23,
		image: imgTwentyThree,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 24,
		image: imgTwentyFour,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
	{
		id: 25,
		image: imgTwentyFive,
		name: "[what happen] How to create",
		price: 2500,
		numberHearth: 236,
	},
]